export const FORM = {
    DATA_REQUEST: 'FORM_DATA_REQUEST',
    DATA_SUCCESS: 'FORM_DATA_SUCCESS',
    DATA_ERROR: 'FORM_DATA_ERROR',
    SUBMIT: 'FORM_SUBMIT',
    LOADING: {
        SHOW: 'FORM_SHOW_LOADING',
        CLOSE: 'FORM_CLOSE_LOADING',
    }
}

export const LEADERBOARD = {
    DATA_REQUEST: 'LEADERBOARD_DATA_REQUEST',
    DATA_SUCCESS: 'LEADERBOARD_DATA_SUCCESS',
    DATA_ERROR: 'LEADERBOARD_DATA_ERROR'
}

export const GAME = {
    GET_CELLSDATA: 'GAME_GET_CELLSDATA',
    CREATE_PICKEDCELL: 'GAME_CREATE_PICKEDCELL',
    ADDPOINT: {
        USER: {
            REQUEST: 'GAME_ADDPOINT_USER_REQUEST',
            SUCCESS: 'GAME_ADDPOINT_USER_SUCCESS'
        },
        COMPUTER: {
            REQUEST: 'GAME_ADDPOINT_COMPUTER_REQUEST',
            SUCCESS: 'GAME_ADDPOINT_COMPUTER_SUCCESS'
        },
    },
    END: 'GAME_END',
    DELETE_STATE: 'GAME_DELETE_STATE',
    RESTART: 'GAME_RESTART'
}