export const FORM = {
    DATA_REQUEST: 'FORM_DATA_REQUEST',
    DATA_SUCCESS: 'FORM_DATA_SUCCESS',
    DATA_ERROR: 'FORM_DATA_ERROR',
    SUBMIT: 'FORM_SUBMIT'
}

export const LEADERBOARD = {
    DATA_REQUEST: 'LEADERBOARD_DATA_REQUEST',
    DATA_SUCCESS: 'LEADERBOARD_DATA_SUCCESS',
    DATA_ERROR: 'LEADERBOARD_DATA_ERROR'
}